### ISSUE TITLE
Allgemein

### ISSUE THREAD

**Issue by PSMSvenja** [pechschwarz-Media/ver#10]
- Der Schlaue Nummer Balken könnt etwas schmaler sein, bitte hier auch ein ähnlicheres Telefon als icon raussuchen

- Vielleicht etwas schmaler, sodass es nicht in die Nummer hereinragt
 ![image](https://user-images.githubusercontent.com/73466320/97192523-44bb4400-17a8-11eb-805c-9034a3c62ac3.png)

- Die Verbindungssuche muss oberhalb vom Footer stoppen, die Abstände müssen dann so angepasst werden, dass weder Text noch Bilder verdeckt werden

- die Schrift auf der gesamten Website erscheint mir groß?

**Comment by PSMJonas** [comment]
Erledigt.
