### ISSUE TITLE
Ergänzender Linienverkehr

### ISSUE THREAD

**Issue by PSMSvenja** [pechschwarz-Media/ver#13]
- Rowjumper beim Hovern/Klicken orange
- Up-Pfeil fehlt
- Bürgerbus-Dropdwoe wie bei Einsatzwagenfahrpläne
- untere Sektion muss sich mit Dropdown wechseln

**Comment by PSMJonas** [comment]
Erledigt. Scroll-Up wird später in der WordPress-Umgebung ergänzt.
