### ISSUE TITLE
Ticketdetailseite

### ISSUE THREAD

**Issue by PSMSvenja** [pechschwarz-Media/ver#16]
Bitte hier mehr am Layout halten

Der Button "Ticket kaufen" muss flexibel sein

![image](https://user-images.githubusercontent.com/73466320/97194449-72a18800-17aa-11eb-84e7-685cb65840d5.png)

**Comment by PSMJonas** [comment]
Erledigt. Die List sollte sich untereinander anordnen, da wir sonst sehr schnell Probleme bezüglich des Responsive-Verhaltens bekommen.
