### ISSUE TITLE
VER-App

### ISSUE THREAD

**Issue by PSMSvenja** [pechschwarz-Media/ver#18]
- Smartphone erscheint mir unscharf, können wir das verbessern? Wenn ja, wie? :)

- bitte Hover auf Pfeil und Optik wie im Layout

- bitte Optik mehr an Layout annähern (insbesondere Aufzählung)

- Die Schrift hier sollte Bold und Regular sein wie im Layout
![image](https://user-images.githubusercontent.com/73466320/97195088-33276b80-17ab-11eb-8a25-5e7aebb7f0f9.png)

**Comment by PSMJonas** [comment]
Erledigt. Aufzählung sollte 1-Spaltig sein, da wir sonst recht schnell responsive Probleme bekommen.
