### ISSUE TITLE
Karriere

### ISSUE THREAD

**Issue by PSMSvenja** [pechschwarz-Media/ver#19]
- Subemenü fehlt
-Unterseite: die Boxen sollten hier natürlich auch immer gleich hoch sein am Ende 
- es fehlt noch die Übersichtseite für Offene Stellen (selbes Template wie für Ausbildung)

**Comment by PSMJonas** [comment]
Erledigt. Submenü wird später in der WordPress-Umgebung ergänzt. Die Seite für die offenen Stellen wird nachher einfach in der WordPress-Umgebung erstellt, da es ja exakt das selbe Template wie "Ausbildung" ist.
