### ISSUE TITLE
Startseite

### ISSUE THREAD

**Issue by PSMSvenja** [pechschwarz-Media/ver#2]
- hast du das extra Layer hinterm Menü angelegt?
- bitte alle Buttons auf der Page einheitlich groß

**Aktuelles Sektion**

- können wir die Buttons hier wie im Layout rechts setzen? Ansonsten gefällt mir der große Abstand unter den Buttons noch nicht und bei dieser Sektion ist natürlich wieder wichtig, dass alle Buttons auf einer Höhe sitzen, egal wie lang der Previewtext ist.

**Fahrplan & Mobilität**

- hier sollte kein graues Layer sein

**Counter**

- hier muss noch der "seit Jahresanfang" Counter angepasst werden. Bitte lass dir von Max die Fahrgastdaten durchgeben

**Comment by PSMJonas** [comment]
Erledigt.
