### ISSUE TITLE
Interaktiver Liniennetzplan

### ISSUE THREAD

**Issue by PSMSvenja** [pechschwarz-Media/ver#20]
der Plan braucht hier noch eine eigene Seite, die kann so aussehen wir die Seite vom Jahresplaner, nur dass dann dort der Liniennetzplan eingebunden wird. ich mein Raphael hatte gesagt, dass wir den Plan easy einbinden könnten:
http://www.ver-netzplan.de/index.php/de/netzplan

**Comment by PSMJonas** [comment]
Erledigt.
