### ISSUE TITLE
Suche

### ISSUE THREAD

**Issue by PSMSvenja** [pechschwarz-Media/ver#23]
Wieso haben wir zwei Suchmasken?

**Comment by PSMJonas** [comment]
Das eine ist das Such-Overlay, wenn man die Suche öffnet. Das andere ist die Ergebnisseite. Hier ist es typisch, dass es hier auch nochmal eine Suche gibt, damit man das Suchwort ggf. anpassen kann.

**Comment by PSMSvenja** [comment]
ok :)
