### ISSUE TITLE
Menü

### ISSUE THREAD

**Issue by PSMSvenja** [pechschwarz-Media/ver#4]
Es wäre cool, wenn man immer nur eine Untersektion öffnen könnte beim Menü, also so, dass sich beim Öffnen einer Sektion die andere, die zuvor offen war automatisch schließt. Vielleicht können wir auch immer den Hintergrund in einem etwas helleren orange darstellen beim Hovern, aktuell ist ja nur der Text immer orange gehovert. Generell scheint das Menü noch etwas buggy?

Teilweise ist das Menü ziemlich gequetscht, vielleicht sollte man früher zum Burgermenü switchen. 
Das Untermenü sollte nie bis ins Logo rutschen

Hier sollte nicht das Submenü mit einem Strick amrkiert werden, sondern einfch nur orange hinterlegt sein:
![image](https://user-images.githubusercontent.com/73466320/97192851-9fed3680-17a8-11eb-8d33-e784615ca00c.png)

**Comment by PSMJonas** [comment]
Erledigt.
