### ISSUE TITLE
Übersichtsseiten

### ISSUE THREAD

**Issue by PSMSvenja** [pechschwarz-Media/ver#6]
Die Kacheln sollten nie alle 3 nebeneinander sein, sondern bitte so wie im Layout

Bitte nie so:  (die letzte Kachel sollte immer über die gesamte Breite gehen, also genauso breit sein wie die beiden Kacheln darüber zusammen)
![image](https://user-images.githubusercontent.com/73466320/97190519-19cff080-17a6-11eb-930c-1e9dbc2f9bcb.png)

**Comment by PSMJonas** [comment]
Erledigt.
