### ISSUE TITLE
Fahrplanauskunft/Abfahrtsmonitor

### ISSUE THREAD

**Issue by PSMSvenja** [pechschwarz-Media/ver#9]
Bitte die Lupe beim Hovern blau. Wenn man das Fullscreenfenster schließt, sollte sich das Kreuz wieder drehen und vll der Kreis um das Kreuz blau

Zeiteinstellung funktioniert noch nicht

Hier sollten wir generell nochmal über das Layout quatschen

**Comment by PSMJonas** [comment]
Erledigt.
